title: SATCOM UHF
description: "Everything about SATCOM"
author:
  name: "SATCOM Pirates"
  url: "https://t.me/Satcom_UHF"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from

# Custom variables
owner : "Satcom Pirates"
year : "2020"
